name: sodium_example
description: Demonstrates how to use the sodium package.
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">3.41.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  sodium: ^3.4.7

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.30.0

flutter:
  uses-material-design: true
