version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/sodium"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/sodium_libs"
    schedule:
      interval: "weekly"
