name: sodium

packages:
  - packages/sodium
  - packages/sodium_libs

scripts:
  get:
    run: >-
      dart pub global run melos exec --no-flutter -- dart pub get &&
      dart pub global run melos exec --flutter -- flutter pub get
    description: Run 'pub get' in all projects

  upgrade:
    run: >-
      dart pub global run melos exec --no-flutter -- dart pub upgrade &&
      dart pub global run melos exec --flutter -- flutter pub upgrade
    description: Run 'pub upgrade' in all projects

  analyze:
    run: >-
      dart pub global run melos exec --no-flutter -- dart analyze --fatal-infos &&
      dart pub global run melos exec --flutter -- flutter analyze
    description: Run 'analyze' in all projects

  outdated:
    run: >-
      dart pub global run melos exec --no-flutter -- dart pub outdated &&
      dart pub global run melos exec --flutter -- flutter pub outdated
    description: Run 'pub outdated' in all projects

  build:
    run: >-
      dart pub global run melos exec --depends-on=build_runner
      -- dart run build_runner build
    description: Run the build runner in all projects

  build:clean:
    run: >-
      dart pub global run melos exec --depends-on=build_runner
      -- dart run build_runner build --delete-conflicting-outputs
    description: Run the build runner in all projects, discarding the previous state

  pre-commit:init:
    run: >-
      bash -c "echo -e
      '#!/bin/sh\nexec dart pub global run melos run pre-commit:run'
      > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"
    description: Setup pre commit hooks

  pre-commit:remove:
    run: rm -f .git/hooks/pre-commit
    description: Remove pre commit hooks

  pre-commit:run:
    run: >-
      dart pub global run melos exec -c1 --no-flutter -- dart run dart_pre_commit &&
      dart pub global run melos exec -c1 --flutter -- flutter pub run dart_pre_commit
    description: Run pre commit hooks in all projects
