name: sodium_libs
version: 4.0.1
description: Flutter companion package to sodium that provides the low-level libsodium binaries for easy use.
homepage: https://github.com/Skycoder42/libsodium_dart_bindings

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"
resolution: workspace

dependencies:
  sodium: ^4.0.3

dev_dependencies:
  dart_pre_commit: ^6.1.3
  dart_test_tools: ^7.2.5

cider:
  link_template:
    tag: https://github.com/Skycoder42/libsodium_dart_bindings/releases/tag/sodium_libs-v%tag%
    diff: https://github.com/Skycoder42/libsodium_dart_bindings/compare/sodium_libs-v%from%...sodium_libs-v%to%
