include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "example/web/**"
    - "lib/src/ffi/bindings/libsodium.ffi.dart"

linter:
  rules:
    comment_references: false
    avoid_catches_without_on_clauses: false
