name: Compile native libsodium binaries

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      # - main
      # - features/isolates
    # paths:
    #   - packages/sodium_libs/libsodium_version.dart
    #   - packages/sodium_libs/tool/libsodium/*
    #   - .github/workflows/libsodium.yaml

env:
  minisignVersion: 0.11

jobs:
  update_binaries:
    name: Update binaries if required
    runs-on: ubuntu-latest
    outputs:
      # only one of the matrix jobs result gets returned
      # but that is okay, also only positive checks update these variables
      # and those are all the same
      modified: ${{ steps.check.outputs.modified }}
      version: ${{ steps.check.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android_arm64_v8a
          - android_armeabi_v7a
          - android_x86_64
          - android_x86
          - windows
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Pull minisign docker image
        run: |
          set -eo pipefail
          docker pull jedisct1/minisign
          echo "MINISIGN_DOCKER=true" >> "$GITHUB_ENV"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: check
        name: Check if upstream stable was updated
        run: dart run tool/libsodium/detect_modified.dart ${{ matrix.platform }}
        working-directory: packages/sodium_libs
      - name: Build updated binaries
        if: steps.check.outputs.modified == 'true'
        run: dart run tool/libsodium/build.dart ${{ matrix.platform }}
        working-directory: packages/sodium_libs
      - name: Create artifact
        if: steps.check.outputs.modified == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: libsodium-${{ matrix.platform }}
          path: ${{ runner.temp }}/libsodium-${{ matrix.platform }}
          if-no-files-found: error
          retention-days: 1

  update_release:
    name: Update release with new binaries
    needs:
      - update_binaries
    if: needs.update_binaries.outputs.modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Pull minisign docker image
        run: docker pull jedisct1/minisign
      - name: Create docker secret for minisign
        run: echo '${{ secrets.MINISIGN_SECRET_KEY }}' | docker secret create minisign-secret-key -
      - name: Download all binary artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create release artifacts
        run: |
          set -eo pipefail
          for artifact in *; do
            tar -cavf "../$artifact.tar.xz" "$artifact"
            docker run --rm \
              --secret minisign-secret-key \
              -v "..:/src" \
              jedisct1/minisign -Ss /run/secrets/minisign-secret-key -m "/src/$artifact.tar.xz"
          done
        working-directory: artifacts
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libsodium-binaries/v${{ needs.update_binaries.outputs.version }}
          name: "[INTERNAL] Precompiled libsodium binaries v${{ needs.update_binaries.outputs.version }}"
          body: Internal release of precompiled libsodium binaries, required for the sodium_libs package.
          prerelease: true
          files: |
            libsodium-*.tar.xz
            libsodium-*.tar.xz.minisig
          fail_on_unmatched_files: true
