name: Compile native libsodium binaries

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      # - main
      # - features/isolates
    # paths:
    #   - packages/sodium_libs/libsodium_version.dart
    #   - packages/sodium_libs/tool/libsodium/*
    #   - .github/workflows/libsodium.yaml

env:
  minisignVersion: 0.11

jobs:
  update_binaries:
    name: Update binaries if required
    outputs:
      # only one of the matrix jobs result gets returned
      # but that is okay, also only positive checks update these variables
      # and those are all the same
      modified: ${{ steps.check.outputs.modified }}
      version: ${{ steps.check.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android_arm64_v8a
          - android_armeabi_v7a
          - android_x86_64
          - android_x86
          - ios
          - ios_simulator_arm64
          - ios_simulator_x86_64
          - macos_arm64
          - macos_x86_64
          - windows

        include:
          - platform: ios
            runs-on: macos-latest
            minisign-brew: true
          - platform: ios_simulator_arm64
            runs-on: macos-latest
            minisign-brew: true
          - platform: ios_simulator_x86_64
            runs-on: macos-latest
            minisign-brew: true
          - platform: macos_arm64
            runs-on: macos-latest
            minisign-brew: true
          - platform: macos_x86_64
            runs-on: macos-latest
            minisign-brew: true
    runs-on: ${{ matrix.runs-on || 'ubuntu-latest' }}
    env:
      MINISIGN_DOCKER: ${{ !matrix.minisign-brew }}
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Install minisign from homebrew
        if: matrix.minisign-brew
        run: brew install minisign
      - name: Pull minisign docker image
        if: "!matrix.minisign-brew"
        run: docker pull jedisct1/minisign
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: check
        name: Check if upstream stable was updated
        run: dart run tool/libsodium/detect_modified.dart ${{ matrix.platform }}
        working-directory: packages/sodium_libs
      - name: Build updated binaries
        if: steps.check.outputs.modified == 'true'
        run: dart run tool/libsodium/build.dart ${{ matrix.platform }}
        working-directory: packages/sodium_libs
      - name: Create artifact
        if: steps.check.outputs.modified == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: libsodium-${{ matrix.platform }}
          path: ${{ runner.temp }}/libsodium-${{ matrix.platform }}
          if-no-files-found: error
          retention-days: 1

  update_release:
    name: Update release with new binaries
    needs:
      - update_binaries
    if: needs.update_binaries.outputs.modified == 'true'
    runs-on: ubuntu-latest
    env:
      MINISIGN_DOCKER: true
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Pull minisign docker image
        run: docker pull jedisct1/minisign
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download all binary artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create docker secret for minisign
        run: echo '${{ secrets.MINISIGN_SECRET_KEY }}' > '${{ runner.temp }}/minisign.key'
      - name: Build release archives
        run: dart run tool/libsodium/publish.dart
        working-directory: packages/sodium_libs
      - name: Cleanup minisign key
        if: always()
        run: shred -fzvu '${{ runner.temp }}/minisign.key'
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libsodium-binaries/v${{ needs.update_binaries.outputs.version }}
          name: "[INTERNAL] Precompiled libsodium binaries v${{ needs.update_binaries.outputs.version }}"
          body: Internal release of precompiled libsodium binaries, required for the sodium_libs package.
          prerelease: true
          files: |
            publish/libsodium-*.tar.xz
            publish/libsodium-*.tar.xz.minisig
          fail_on_unmatched_files: true
