name: Update libsodium

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - hooks
    paths:
      - packages/sodium/tool/libsodium
      - .github/workflows/libsodium_update.yaml
  schedule:
    - cron: "47 2 * * 2"

jobs:
  update_if_modified:
    name: Check if binaries need to be updated
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: write
      pull-requests: write
      actions: write
    env:
      NIX_SKIP_SODIUM_BUILD_HOOKS: 1
    steps:
      - name: Install Flutter-SDK (stable)
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install dart dependencies
        run: dart pub get
        working-directory: packages/sodium
      - id: check
        name: Check if upstream stable archives have been update
        run: dart run tool/libsodium/detect_modified.dart
        working-directory: packages/sodium
      - id: sync-changes
        name: Synchronize upstream changes
        if: steps.check.outputs.modified == 'true'
        run: dart run tool/libsodium/sync_libsodium_changes.dart
        working-directory: packages/sodium
      - name: Update changelog and bump build number
        if: steps.check.outputs.modified == 'true'
        run: |
          set -euo pipefail
          dart pub global run dart_test_tools:cider log changed 'Updated embedded libsodium binaries'
          dart pub global run dart_test_tools:cider bump build
          dart pub global run dart_test_tools:cider release
        working-directory: packages/sodium
      - name: Create validated pull request
        if: steps.check.outputs.modified == 'true'
        uses: Skycoder42/dart_test_tools/.github/actions/create-validated-pr@main
        with:
          prBranchName: last-modified-${{ github.run_id }}
          prCommitMessage: Update last-modified.txt
          prTitle: Bump version for new stable libsodium
          prBody: |
            Upstream archive for libsodium v${{ steps.check.outputs.version }} has changed!
            The new timestamp is: `${{ steps.check.outputs.last-modified }}`
            Modified upstream files: ${{ steps.sync-changes.outputs.modified-files }}
          validationWorkflow: sodium_ci.yaml
          validationTimeout: 7200
