name: Update libsodium

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/sodium/tool/libsodium
      - .github/workflows/libsodium_update.yaml
  schedule:
    - cron: "47 2 * * 2"

jobs:
  detect_modified:
    name: Check if binaries need to be updated
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.check.outputs.modified }}
      version: ${{ steps.check.outputs.version }}
      last-modified: ${{ steps.check.outputs.last-modified }}
    steps:
      - name: Install Flutter-SDK (stable)
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install dart dependencies
        run: dart pub get
        working-directory: packages/sodium
      - id: check
        name: Check if upstream stable archives have been update
        run: dart run tool/libsodium/detect_modified.dart
        working-directory: packages/sodium

  create_update_pr:
    name: Create update PR
    needs:
      - detect_modified
    if: needs.detect_modified.outputs.modified == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install Flutter-SDK (stable)
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Install dart_test_tools
        run: dart pub global activate dart_test_tools
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Install dart dependencies
        run: dart pub get
        working-directory: packages/sodium_libs
      - name: Update last-modified.txt
        run: >-
          echo '${{ needs.detect_modified.outputs.last-modified }}'
          > tool/libsodium/.last-modified.txt
        working-directory: packages/sodium_libs
      - name: Update changelog and bump build number
        run: |
          set -euo pipefail
          dart pub global run dart_test_tools:cider log changed 'Updated embedded libsodium binaries'
          dart pub global run dart_test_tools:cider bump build
          dart pub global run dart_test_tools:cider release
        working-directory: packages/sodium_libs
      - id: create-pull-request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update last-modified.txt
          branch: last-modified-${{ github.run_id }}
          delete-branch: true
          assignees: Skycoder42
          title: Bump version for new stable libsodium
          body: |
            Upstream archive for libsodium v${{ needs.detect_modified.outputs.version }} has changed!
            The new timestamp is: `${{ needs.detect_modified.outputs.last-modified }}`
          token: ${{ secrets.GH_PAT }}
      - name: Mention assignees
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          message: Your review has been requested @Skycoder42
