name: Compile native libsodium binaries

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    #   - main
    # paths:
    #   - packages/sodium_libs/libsodium_version.dart
    #   - packages/sodium_libs/tool/libsodium/*
    #   - .github/workflows/libsodium.yaml

jobs:
  detect_modified:
    name: Check if binaries need to be updated
    runs-on: ubuntu-latest
    outputs:
      modified: ${{ steps.check.outputs.modified }}
      version: ${{ steps.check.outputs.version }}
      last-modified-content: ${{ steps.check.outputs.last-modified-content }}
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: check
        name: Check if upstream stable archives have been update
        run: dart run tool/libsodium/detect_modified.dart
        working-directory: packages/sodium_libs

  build:
    name: Update binaries if required
    needs:
      - detect_modified
    if: needs.detect_modified.outputs.modified == 'true'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - android_arm64_v8a
          - android_armeabi_v7a
          - android_x86_64
          - android_x86
          - ios_arm64
          - ios_simulator_arm64
          - ios_simulator_x86_64
          - macos_arm64
          - macos_x86_64
          - windows

        include:
          - platform: ios_arm64
            runs-on: macos-latest
          - platform: ios_simulator_arm64
            runs-on: macos-latest
          - platform: ios_simulator_x86_64
            runs-on: macos-latest
          - platform: macos_arm64
            runs-on: macos-latest
          - platform: macos_x86_64
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on || 'ubuntu-latest' }}
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install minisign
        uses: ./.github/actions/install-minisign
      - name: Build libsodium binaries
        run: dart run tool/libsodium/build.dart ${{ matrix.platform }}
        working-directory: packages/sodium_libs
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: libsodium-${{ matrix.platform }}
          path: ${{ runner.temp }}/libsodium-${{ matrix.platform }}
          if-no-files-found: error
          retention-days: 1

  update_release:
    name: Update release with new binaries
    needs:
      - detect_modified
      - build
    if: needs.detect_modified.outputs.modified == 'true'
    runs-on: macos-latest # needed for lipo
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install minisign
        uses: ./.github/actions/install-minisign
      - name: Download all binary artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create secret key for minisign
        run: echo '${{ secrets.MINISIGN_SECRET_KEY }}' > '${{ runner.temp }}/minisign.key'
      - name: Build release archives
        run: dart run tool/libsodium/publish.dart
        working-directory: packages/sodium_libs
      - name: Cleanup minisign key
        if: always()
        run: rm -f '${{ runner.temp }}/minisign.key'
      - name: Create or update release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: libsodium-binaries/v${{ needs.detect_modified.outputs.version }}
          name: "[INTERNAL] Precompiled libsodium binaries v${{ needs.detect_modified.outputs.version }}"
          body: Internal release of precompiled libsodium binaries, required for the sodium_libs package.
          prerelease: true
          files: publish/*
          fail_on_unmatched_files: true

  update_last_modified:
    name: Update last-modified.txt
    needs:
      - detect_modified
      - update_release
    if: needs.detect_modified.outputs.modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Install Dart-SDK (stable)
        uses: dart-lang/setup-dart@v1
      - name: Install cider
        run: dart pub global activate cider
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Update last-modified.txt
        run: |
          cat << 'EOF' > tool/libsodium/.last-modified.txt
          ${{ needs.detect_modified.outputs.last-modified-content }}
          EOF
        working-directory: packages/sodium_libs
      - name: Bump build number
        run: dart pub global run cider bump build
        working-directory: packages/sodium_libs
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update last-modified.txt
          branch: last-modifed-${{ github.run_id }}
          delete-branch: true
          title: Update last-modified.txt to reflect upstream changes
          body: |
            Upstream archives have changed. New modified timestamps are:

            ```
            ${{ needs.detect_modified.outputs.last-modified-content }}
            ```
          token: ${{ secrets.GH_PAT }}
