name: CI/CD for sodium_libs

on:
  workflow_dispatch:
  push:
    paths:
      - packages/sodium_libs/**
      - .github/workflows/sodium_libs_ci.yaml
      - .github/workflows/sodium_libs_cd.yaml
      - "!packages/sodium_libs/tool/libsodium/**"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  package_sodium:
    name: Package sodium
    uses: Skycoder42/dart_test_tools/.github/workflows/package.yml@main
    with:
      workingDirectory: packages/sodium
      buildRunner: true

  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    needs:
      - package_sodium
    with:
      workingDirectory: packages/sodium_libs
      artifactDependencies: package_sodium
      unitTestPaths: ""
      integrationTestProject: example
      integrationTestPaths: integration_test
      integrationTestSetup: >-
        {
          "android": "dart run tool/libsodium/download.dart android",
          "ios": "dart run tool/libsodium/download.dart ios",
          "linux": "dart run tool/libsodium/download.dart linux",
          "macos": "dart run tool/libsodium/download.dart macos",
          "windows": "dart run tool/libsodium/download.dart windows",
          "web": "cd example && dart run sodium_libs:update_web --sumo"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/sodium_libs
      tagPrefix: sodium_libs-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
