name: CI/CD for sodium

on:
  workflow_dispatch:
  push:
    paths:
      - "packages/sodium/**"
      - ".github/workflows/sodium_ci.yaml"
      - ".github/workflows/sodium_cd.yaml"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      workingDirectory: packages/sodium
      env: >-
        {
          "NIX_SKIP_SODIUM_BUILD_HOOKS": "1",
          "NIX_HOOKS_ENABLE_DEBUG_LOGGING": "1"
        }
      needsFlutterSdk: true
      buildRunner: true
      unitTestPaths: -P unit
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.ffi.dart"
        "**/*.ffi.wrapper.dart"
        "**/*.js.dart"
      integrationTestPaths: -P integration
      integrationTestSetup: >-
        {
          "linux": "dart run tool/integration/setup_hooks.dart",
          "windows": "dart run tool/integration/setup_hooks.dart",
          "macos": "dart run tool/integration/setup_hooks.dart",
          "web": "dart run tool/integration/setup_web.dart"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/sodium
      tagPrefix: sodium-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
