name: CD - Publish to pub.dev

on:
  push:
    tags:
      - "sodium-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      tagPrefix: sodium-v
      flutter: true
      workingDirectory: packages/sodium
      env: >-
        {
          "NIX_SKIP_SODIUM_BUILD_HOOKS": "1",
          "NIX_HOOKS_ENABLE_DEBUG_LOGGING": "1"
        }
      buildRunner: true
      prePublish: dart run tool/download_libsodium.dart
