name: CI/CD for sodium_libs

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    paths:
      - "packages/sodium_libs/**"
      - ".github/workflows/sodium_libs_ci.yaml"
  pull_request:
    branches:
      - "**"
    paths:
      - "packages/sodium_libs/**"
      - ".github/workflows/sodium_libs_ci.yaml"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: packages/sodium_libs
      unitTestPaths: ""
      integrationTestProject: "example"
      integrationTestPaths: "integration_test/app_test.dart"
      integrationTestSetup: >-
        {
          "android": "dart run tool/setup_android.dart",
          "linux": "sudo apt-get -qq install libsodium-dev",
          "windows": "choco install minisign -y",
          "macos": "brew install libsodium",
          "web": "cd example && flutter pub run sodium_libs:update_web --sumo"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/sodium_libs
      tagPrefix: sodium_libs-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
