name: CD - Publish to pub.dev

on:
  push:
    tags:
      - "sodium-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      tagPrefix: sodium-v
      workingDirectory: packages/sodium
      buildRunner: true
