name: CD - Publish to pub.dev

on:
  push:
    tags:
      - "sodium_libs-v*"

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      environment: pub-deploy
      tagPrefix: sodium_libs-v
      flutter: true
      workingDirectory: packages/sodium_libs
      prePublish: tool/setup/linux.sh
