name: CI/CD for sodium_libs

on:
  workflow_dispatch:
  push:
    paths:
      - packages/sodium_libs/**
      - .github/workflows/sodium_libs_ci.yaml
      - .github/workflows/sodium_libs_cd.yaml
      - "!packages/sodium_libs/tool/libsodium/**"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/flutter.yml@main
    with:
      workingDirectory: packages/sodium_libs
      unitTestPaths: ""
      integrationTestProject: "example"
      integrationTestPaths: "integration_test/app_test.dart"
      integrationTestSetup: >-
        {
          "android": "tool/setup/macos.sh android",
          "ios": "tool/setup/macos.sh ios",
          "linux": "tool/setup/linux.sh linux",
          "macos": "tool/setup/macos.sh macos",
          "windows": "bash tool/setup/windows.sh windows",
          "web": "cd example && flutter pub run sodium_libs:update_web --sumo"
        }

  cd:
    name: CD
    uses: Skycoder42/dart_test_tools/.github/workflows/release.yml@main
    needs:
      - ci
    with:
      workingDirectory: packages/sodium_libs
      tagPrefix: sodium_libs-v
    secrets:
      githubToken: ${{ secrets.GH_PAT }}
