name: "[sodium_libs] CD"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to be deployed
        required: true

jobs:
  publish:
    name: Publish
    uses: Skycoder42/dart_test_tools/.github/workflows/publish.yml@main
    permissions:
      id-token: write
    with:
      tagPrefix: sodium_libs-v
      version: ${{ inputs.version }}
      flutter: true
      workingDirectory: packages/sodium_libs
      env: >-
        {
          "NIX_SKIP_SODIUM_BUILD_HOOKS": "1"
        }
